Title = "MercuryLoggerSpec"

[Test_Msg]
    Address = "192.168.3.249"
    Port = 5555
    Message = "TestMsg()" # File name specifying the ProtoBuf message struct

[Motor_Msg]
    Address = "192.168.3.249"
    Port = 5556
    Message = 256 # Number of bytes which contains the message